### ISSUE TITLE
今年要打破的 10 种不良 TypeScript 习惯

### ISSUE THREAD

**Issue by PeterChen1997** [highestop/yfd-tech-reading#40]
https://startup-cto.net/10-bad-typescript-habits-to-break-this-year/

**Comment by highestop** [comment]
- 判断类型时，可以借助 assertion，起到的作用类似于 `** is **` & `throw new Error`
- optional 有时是必须的，前提是每个 optional 都是独立的。如果相互有连带关系，推荐分型写 extends 然后用 is Function 去 assert 他们
